name: unit_tests

# do the following jobs on push and on pull requests
on: [push, pull_request]

# define the jobs
jobs:
  unit-tests:
    name: ${{ matrix.config.os }} (${{ matrix.config.py }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config: 
        - {os: windows-latest, py: "3.12.3"}
        - {os: macOS-latest, py: "3.12.3"}
        - {os: ubuntu-latest, py: "3.12.3"}
        - {os: ubuntu-latest, py: "3.12.3"}
        - {os: ubuntu-latest, py: "3.12.3"}
    steps: 
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.config.py }}"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: run pytest for ${{ matrix.python-version }}
        run: pytest
